name = "socialnest"
main = "./index.js"
compatibility_date = "2025-04-16"

# Enable observability for logging
[observability.logs]
enabled = true

[[kv_namespaces]]
binding = "SESSIONS"
id = "36c4bd45cf1d4a9f92206321ecc0f91e"

[[d1_databases]]
binding = "DB"
database_name = "socialnest"
database_id = "9a60624f-a1da-444f-9d8d-42e92528f44d"