name = "socialnest"
main = "./index.js"
compatibility_date = "2025-04-16"

# Enable observability for logging
[observability.logs]
enabled = true

[vars]
TWITTER_CLIENT_ID = "env.TWITTER_CLIENT_ID"
TWITTER_CLIENT_SECRET = "env.TWITTER_CLIENT_SECRET"
TWITTER_CALLBACK_URL = "env.TWITTER_CALLBACK_URL"

[[d1_databases]]
binding = "DB"
database_name = "socialnest"
database_id = "9a60624f-a1da-444f-9d8d-42e92528f44d"
